In [4]:
#Варіант 20

#Завдання 1 Створіть одновимірний масив (вектор) з сумами кожного числа та його попереднього, починаючи з 1, та виведіть його значення.
# Кількість елементів масиву
n = 10

# Ініціалізуємо порожній список
vector = []

# Початкове значення попереднього числа
prev = 0

# Заповнюємо масив
for i in range(1, n + 1):
    current = i + prev
    vector.append(current)
    prev = i  # оновлюємо попереднє число

# Виводимо масив
print("Масив квадратних коренів:")
print(vector)



Масив квадратних коренів:
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [5]:
#Завдання 2
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових дійсних чисел від 1 до 10.
import random  # підключаємо модуль для випадкових чисел

# Розмір матриці
rows = 3
cols = 3

# Створюємо матрицю 3x3 з випадковими числами від 1 до 10
matrix = [[random.uniform(1, 10) for _ in range(cols)] for _ in range(rows)]

# Виводимо матрицю
for row in matrix:
    print(row)


[9.69108334489896, 9.427890065775932, 1.9623425266101626]
[3.147507396629239, 5.8735674393262665, 4.078426976293694]
[9.180867576976844, 7.290176867900197, 7.840216436112741]


In [7]:
#Завдання 3
#Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 100 та виведіть мін значення
import random

# Розмір матриці
rows = 3
cols = 3

# Створюємо матрицю 3x3 з випадковими числами від 1 до 100
matrix = [[random.randint(1, 100) for _ in range(cols)] for _ in range(rows)]

# Виводимо матрицю
print("Матриця:")
for row in matrix:
    print(row)

# Знаходимо мінімальне значення
min_value = min(min(row) for row in matrix)
print("\nМінімальне значення в матриці:", min_value)


Матриця:
[68, 27, 15]
[43, 41, 11]
[73, 57, 22]

Мінімальне значення в матриці: 11


In [9]:
#Завдання 4
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5
import random

# Розмір матриці
rows = 4
cols = 4

# Створюємо матрицю 4x4 з випадковими числами від 0 до 1
matrix = [[random.random() for _ in range(cols)] for _ in range(rows)]

# Виводимо матрицю
print("Матриця:")
for row in matrix:
    print(row)

# Рахуємо кількість елементів > 0.5
count = sum(1 for row in matrix for elem in row if elem > 0.5)

print("\nКількість елементів, що більше 0.5:", count)


Матриця:
[0.6493051220467821, 0.8022176077245232, 0.21115086644784287, 0.2058177881429054]
[0.7181427007347184, 0.4582734158601445, 0.0954861169303427, 0.2918233847450936]
[0.5286821586144824, 0.44609238093966486, 0.7189678844763647, 0.9370610437822553]
[0.7084505607308152, 0.5147836664356203, 0.6276679886196229, 0.5697262223939962]

Кількість елементів, що більше 0.5: 10


In [11]:
#Завдання 5
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
import random

# Розмір масивів
n = 4

# Створюємо два масиви з випадковими цілими числами від -10 до 10
array1 = [random.randint(-10, 10) for _ in range(n)]
array2 = [random.randint(-10, 10) for _ in range(n)]

# Виводимо масиви
print("Масив 1:", array1)
print("Масив 2:", array2)

# Поелементне додавання
addition = [a + b for a, b in zip(array1, array2)]
print("Додавання:", addition)

# Поелементне віднімання
subtraction = [a - b for a, b in zip(array1, array2)]
print("Віднімання:", subtraction)

# Поелементне множення
multiplication = [a * b for a, b in zip(array1, array2)]
print("Множення:", multiplication)


Масив 1: [6, 4, 6, -9]
Масив 2: [-8, -9, -7, 10]
Додавання: [-2, -5, -1, 1]
Віднімання: [14, 13, 13, -19]
Множення: [-48, -36, -42, -90]


In [12]:
#Завдання 6
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 20 та знайдіть їх добуток
import random

# Розмір матриць
n = 3

# Створюємо дві матриці 3x3 з випадковими числами від 1 до 20
matrix1 = [[random.randint(1, 20) for _ in range(n)] for _ in range(n)]
matrix2 = [[random.randint(1, 20) for _ in range(n)] for _ in range(n)]

# Виводимо матриці
print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

# Ініціалізуємо матрицю для добутку
product = [[0 for _ in range(n)] for _ in range(n)]

# Матричне множення
for i in range(n):
    for j in range(n):
        for k in range(n):
            product[i][j] += matrix1[i][k] * matrix2[k][j]

# Виводимо результат
print("\nДобуток матриць:")
for row in product:
    print(row)



Матриця 1:
[11, 20, 5]
[18, 2, 12]
[16, 14, 14]

Матриця 2:
[14, 2, 11]
[6, 2, 16]
[9, 7, 18]

Добуток матриць:
[319, 97, 531]
[372, 124, 446]
[434, 158, 652]


In [13]:
#Завдання7
#Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 4 та перемножте їх між собою.
import random

# Розміри матриць
rows1, cols1 = 2, 3
rows2, cols2 = 3, 3

# Створюємо матриці з випадковими цілими числами від 1 до 4
matrix1 = [[random.randint(1, 4) for _ in range(cols1)] for _ in range(rows1)]
matrix2 = [[random.randint(1, 4) for _ in range(cols2)] for _ in range(rows2)]

# Виводимо матриці
print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

# Ініціалізуємо матрицю для добутку (2x3 * 3x3 = 2x3)
product = [[0 for _ in range(cols2)] for _ in range(rows1)]

# Матричне множення
for i in range(rows1):
    for j in range(cols2):
        for k in range(cols1):  # або rows2
            product[i][j] += matrix1[i][k] * matrix2[k][j]

# Виводимо результат
print("\nДобуток матриць:")
for row in product:
    print(row)


Матриця 1:
[3, 2, 3]
[3, 1, 3]

Матриця 2:
[4, 2, 3]
[2, 3, 2]
[4, 3, 2]

Добуток матриць:
[28, 21, 19]
[26, 18, 17]


In [14]:
#Завдання 8
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю
import numpy as np

# Створюємо матрицю 3x3 з випадковими цілими числами від 1 до 7
matrix = np.random.randint(1, 8, size=(3, 3))

print("Матриця 3x3:")
print(matrix)

# Знаходимо обернену матрицю
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(np.round(inverse_matrix, 2))  # округлюємо до 2 знаків після коми
except np.linalg.LinAlgError:
    print("\nМатриця вироджена, оберненої матриці не існує.")


Матриця 3x3:
[[6 1 6]
 [7 7 1]
 [4 1 4]]

Обернена матриця:
[[ 2.25  0.17 -3.42]
 [-2.    0.    3.  ]
 [-1.75 -0.17  2.92]]


In [15]:
#Завдання 9
#Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.
import random

# Розмір матриці
rows = 4
cols = 4

# Створюємо матрицю 4x4 з випадковими числами 0 або 1
matrix = [[random.randint(0, 1) for _ in range(cols)] for _ in range(rows)]

# Виводимо початкову матрицю
print("Початкова матриця:")
for row in matrix:
    print(row)

# Транспонування матриці
transposed = [[matrix[j][i] for j in range(rows)] for i in range(cols)]

# Виводимо транспоновану матрицю
print("\nТранспонована матриця:")
for row in transposed:
    print(row)


Початкова матриця:
[1, 1, 0, 0]
[0, 0, 1, 1]
[0, 0, 0, 0]
[1, 0, 0, 1]

Транспонована матриця:
[1, 0, 0, 1]
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 1, 0, 1]


In [16]:
#Завдання 10
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор.

import numpy as np

# Створюємо матрицю 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)

# Створюємо вектор 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

print("Матриця 3x4:")
print(np.round(matrix, 2))

print("\nВектор 4x1:")
print(np.round(vector, 2))

# Добуток матриці на вектор
product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(np.round(product, 2))



Матриця 3x4:
[[0.93 0.47 0.01 0.29]
 [0.27 0.37 0.1  0.75]
 [0.21 0.39 0.08 0.8 ]]

Вектор 4x1:
[[0.91]
 [0.98]
 [0.84]
 [0.98]]

Добуток матриці на вектор:
[[1.58]
 [1.43]
 [1.43]]


In [17]:
#Завдання 11
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор.

import numpy as np

# Створюємо матрицю 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створюємо вектор 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3, 1)

print("Матриця 2x3:")
print(np.round(matrix, 2))

print("\nВектор 3x1:")
print(np.round(vector, 2))

# Добуток матриці на вектор
product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(np.round(product, 2))


Матриця 2x3:
[[0.36 0.23 0.35]
 [0.14 0.3  0.63]]

Вектор 3x1:
[[0.21]
 [0.18]
 [0.44]]

Добуток матриці на вектор:
[[0.27]
 [0.37]]


In [18]:
#Завдання 12
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці.

import random

# Розмір матриць
n = 3

# Створюємо дві матриці 3x3 з випадковими цілими числами від 1 до 5
matrix1 = [[random.randint(1, 5) for _ in range(n)] for _ in range(n)]
matrix2 = [[random.randint(1, 5) for _ in range(n)] for _ in range(n)]

# Виводимо матриці
print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

# Обчислюємо добуток елементів головної діагоналі другої матриці
diagonal_product = 1
for i in range(n):
    diagonal_product *= matrix2[i][i]

print("\nДобуток елементів діагоналі другої матриці:", diagonal_product)


Матриця 1:
[5, 3, 4]
[4, 4, 2]
[5, 4, 3]

Матриця 2:
[1, 5, 2]
[3, 5, 3]
[5, 2, 5]

Добуток елементів діагоналі другої матриці: 25


In [20]:
#Завдання 13
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 5 та знайдіть різницю їх елементів.
import random

# Розмір матриць
n = 4

# Створюємо дві матриці 4x4 з випадковими цілими числами від 1 до 5
matrix1 = [[random.randint(1, 5) for _ in range(n)] for _ in range(n)]
matrix2 = [[random.randint(1, 5) for _ in range(n)] for _ in range(n)]

# Виводимо матриці
print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

# Поелементна різниця матриць
difference = [[matrix1[i][j] - matrix2[i][j] for j in range(n)] for i in range(n)]

# Виводимо результат
print("\nРізниця матриць (Matrix1 - Matrix2):")
for row in difference:
    print(row)


Матриця 1:
[1, 3, 2, 4]
[2, 3, 5, 1]
[1, 1, 5, 2]
[4, 4, 5, 3]

Матриця 2:
[4, 1, 1, 5]
[3, 4, 1, 4]
[1, 2, 5, 2]
[5, 2, 3, 1]

Різниця матриць (Matrix1 - Matrix2):
[-3, 2, 1, -1]
[-1, -1, 4, -3]
[0, -1, 0, 0]
[-1, 2, 2, 2]


In [21]:
#Завдання 14
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 10 та знайдіть найменший елемент матриці.
import random

# Розмір матриці
n = 3

# Створюємо матрицю 3x3 з випадковими цілими числами від 1 до 10
matrix = [[random.randint(1, 10) for _ in range(n)] for _ in range(n)]

# Виводимо матрицю
print("Матриця 3x3:")
for row in matrix:
    print(row)

# Знаходимо найменший елемент матриці
min_value = min(min(row) for row in matrix)

print("\nНайменший елемент матриці:", min_value)


Матриця 3x3:
[2, 4, 7]
[9, 4, 8]
[2, 10, 9]

Найменший елемент матриці: 2


In [32]:
#Завдання 15
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
#елементів в кожному рядку матриці
import random

# Розмір матриці
rows = 3
cols = 3

# Створюємо матрицю 3x3 з випадковими дійсними числами від -2 до 2
matrix = [[random.uniform(-2, 2) for _ in range(cols)] for _ in range(rows)]

# Виводимо матрицю
print("Матриця 3x3:")
for row in matrix:
    print([round(elem, 2) for elem in row])

# Створюємо вектор-стовпчик з кількістю ненульових елементів у кожному рядку
vector_column = [[sum(1 for elem in row if elem != 0)] for row in matrix]

print("\nВектор-стовпчик (кількість ненульових елементів у кожному рядку):")
for val in vector_column:
    print(val)


Матриця 3x3:
[0.9, 0.37, 1.7]
[0.73, -1.76, 0.04]
[0.13, -1.55, 1.84]

Вектор-стовпчик (кількість ненульових елементів у кожному рядку):
[3]
[3]
[3]


In [33]:
#Висновок
#В цій лабораторній роботі я пригадала основні елементи лінійної алгебри, та написання програм для розв'язування цих самих лінійних задач


